import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'login': "Login",
          'register_now': "Register now",
          'are_new_user': "Are you a new user?",
          'register_new_family': "Register New Family",
          'user_type': "User type",
          'enter_hometown_add': "Enter hometown address",
          'country': "Country",
          'state': "State",
          'district': "District",
          'village_city': "Village/City/Town",
          'what_cast': "What cast do you belong?",
          'area': "Area",
          'pin_code': "Pin code",
          'house_number': "House Number",
          'add_society': "+ Add Society",
          'next': "Next",
          'new_society': "New Society",
          'society_name': "Society Name",
          'if_the_society':
              "If the society is not available in the list then click here to register the society first.",
          'lets_add': "Let’s add family members",
          'family_number': "Family identity number",
          'this_will_be': "This will be generated once you add a family member",
          'enter_otp': "Enter OTP",
          'enter_mobile_number': "Mobile number",
          'request_otp': "Request OTP",
          'change_language': "Change Language",
          'how_signup': "How would you like to Signup?",
          'new_family': "New Family",
          'let_add_family_members': "Let’s add family members",
          'family_identity_number': "Family identity number",
          'start_add': "Start adding family members",
          'once_you_add':
              "Once you add family member, family id will be generated",
          'add_member': "+ Add Member",
          'renter': "Renter",
          'relative': "Relative",
          'hometown ': "Hometown ",
          'current': "Current",
          'other': "Other",
          'add_hometown_add':"Add hometown address",
          'add_new_family':"Add New Family Member",
          'first_name':"First name",
          'last_name':"Last name",
          'father_name':"Fathers Name",
          'mother_name':"Mothers Name",
          'male':"Male",
          'female':"Female",
          'gender':"Gender",
          'dob':"Date of Birth",
          'aadhar_card_details':"Aadhar card details",
          'aadhar_number':"Aadhar number",
          'front_photo':"Front photo of aadhar card - upload",
          'tap_upload':"Tap to upload",
          'back_photo':"Back photo of aadhar card - upload",
          'What_do_you_want_to_talk_about?':"What do you want to talk about?",
          'vote_which_is_better?' : "Vote which is better?",
          'create_poll' : "Create Poll",
          'gallery' : "Gallery",
          'addVideo' : "Add Video",
          'place' : "Place",
          'addSome' : "Add Some",
          'record' : "Record",
          'post' : "Post",
          'vote_which_image_is_better?' : "Vote which image is better?",
          'poll_options' : "Poll Options",
          'add_option' : "+ Add Option",
          'business' : "Business",
          'location' : "Location",
          'city' : "City",
          'enter_your_business_information' : 'Enter your Business Information',
          'type' : 'Type',
          'company' : 'Company',
          'company_name' : 'Company Name',
          'business_name' : 'Business Name',
          'business_address' : 'Business Address',
          'choose_family_member_relation' : 'Choose family member relation',
          'upload_your_business_logo' : 'Upload your Business Logo',
          'village_city_town' : 'Village/City/Town',
          'business_category' : 'Business Category',
          'description' : 'Description',
          'experience_in_business' : 'Experience in Business',
          'business_partner' : 'Business Partner',
          'social_account_links' : 'Social Account Links',
          'facebook' : 'Facebook',
          'instagram' : 'Instagram',
          'linkedIn' : 'LinkedIn',
          'pinterest' : 'Pinterest',
          'skype' : 'Skype',
          'add_your_skills_or_talent' : 'Add your Skills or Talent',
          'added' : 'Added',
          'checkout_this_video' : 'Checkout this video',
          'my_home_interior_ideas_and_concepts' : 'My home interior ideas and concepts',
          'create_a_new_book' : 'Create a new Book',
          'title' : 'Title',
          'book_title' : 'Book Title',
          'publisher_type' : 'Publisher Type',
          'author' : 'Author',
          'member' : 'Member',
          'price_type' : 'Price Type',
          'free' : 'Free',
          'paid' : 'Paid',
          'book_price_(₹)' : 'Book Price (₹)',
           'website_url' : 'Website Url',
           'book_language' : 'Book Language',
           'book_category' : 'Book Category',
           'book_edition' : 'Book Edition',
           'upload_your_PDF' : 'Upload your Chapter PDF (Optional)',
           'tap_to_upload' : 'Tap to upload',
           'create' : 'Create',
           'add_chapter' : 'Add Chapter',
           'chapter_title' : 'Chapter Title',
           'add' : 'Add',
           'create_a_new_group' : 'Create a  new group',
           'group_name' : 'Group Name',
           'upload_your_group_photo' : 'Upload your group photo',
           'about_of_group' : 'About of group',
           'group_captain' : 'Group Captain',
           'search' : 'Search',
           'choose_group_type' : 'Choose group type',
           'address' : 'Address',
           'category' : 'Category',
           'group_public_or_private' : 'Group Public or Private',
           'new_product' : 'New Product',
           'product_name' : 'Product Name',
           'product_price' : 'Product Price',
           'product_category' : 'Product Category',
           'new' : 'New',
           'used' : 'Used',
           'upload_your_product_photos' : 'Upload your Product Photos',
           'upload_your_product_video' : 'Upload your Product Video',
           'new_property' : 'New Property',
           'property_name' : 'Property Name',
           'property_price' : 'Property Price',
           'property_category' : 'Property Category',
           'sale' : 'Sale',
           'rent' : 'Rent',
           'upload_your_property_photos' : 'Upload your Property Photos',
           'upload_your_Property_video' : 'Upload your Property Video',
           'new_offer' : 'New Offer',
           'offer_title' : 'Offer Title',
           'offer_promocode' : 'Offer Promocode (Optional)',
           'start_date' : 'Start Date',
           'end_date' : 'End Date',
           'offer_category' : 'Offer Category',
           'upload_your_offer_photos' : 'Upload your Offer Photos',
           'upload_your_offer_video' : 'Upload your Offer Video',
           'create_a_new_blog' : 'Create a New Blog',
           'blog_title' : 'Blog Title',
           'blog_keywords' : 'Blog Keywords',
           'upload_your_blog_photos' : 'Upload your Blog Photos',
           'upload_your_blog_video' : 'Upload your Blog Video',
           'new_broadcast' :  'New Broadcast',
           'broadcast_title' : 'Broadcast Title',
           'broadcast_message' : 'Broadcast Message',
           'broadcast_for_location_wise_member' : 'Broadcast For Location wise Member',
           'broacast' : 'Broacast'
          'already_registered_family':"Already registered family",
          'society_registration':"Society Registration",
          'select_state':"Select state",
          'search_state':"Search state",
          'search_country':"Search country",
          'search_village':"Search village",
          'select_country':"Select country",
          'select_district':"Select district",
          'select_village':"Select village",
          'add_new_society':"+ Add New Society",
          'select_society':"Select rociety",
          'search_society':"Search rociety",
          'select_religion':"Select religion",
          'search_religion':"Search religion",



        }
      };
}
