import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'login': "Login",
          'register_now': "Register now",
          'are_new_user': "Are you a new user?",
          'register_new_family': "Register New Family",
          'user_type': "User type",
          'enter_hometown_add': "Enter hometown address",
          'country': "Country",
          'state': "State",
          'district': "District",
          'village_city': "Village/City/Town",
          'what_cast': "What cast do you belong?",
          'area': "Area",
          'pin_code': "Pin code",
          'house_number': "House Number",
          'add_society': "+ Add Society",
          'next': "Next",
          'new_society': "New Society",
          'society_name': "Society Name",
          'if_the_society':
              "If the society is not available in the list then click here to register the society first.",
          'lets_add': "Let’s add family members",
          'family_number': "Family identity number",
          'this_will_be': "This will be generated once you add a family member",
          'enter_otp': "Enter OTP",
          'enter_mobile_number': "Mobile number",
          'request_otp': "Request OTP",
          'change_language': "Change Language",
          'how_signup': "How would you like to Signup?",
          'new_family': "New Family",
          'let_add_family_members': "Let’s add family members",
          'family_identity_number': "Family identity number",
          'this_will_be': "This will be generated once you add a family member",
          'start_add': "Start adding family members",
          'once_you_add':
              "Once you add family member, family id will be generated",
          'add_member': "+ Add Member",
          'renter': "Renter",
          'relative': "Relative",
          'hometown ': "Hometown ",
          'current': "Current",
          'other': "Other",
          'add_hometown_add':"Add hometown address",
          'add_new_family':"Add New Family Member",
          'first_name':"First name",
          'last_name':"Last name",
          'father_name':"Fathers Name",
          'mother_name':"Mothers Name",
          'male':"Male",
          'female':"Female",
          'gender':"Gender",
          'dob':"Date of Birth",
          'aadhar_card_details':"Aadhar card details",
          'aadhar_number':"Aadhar number",
          'front_photo':"Front photo of aadhar card - upload",
          'tap_upload':"Tap to upload",
          'back_photo':"Back photo of aadhar card - upload",
        }
      };
}
